### ISSUE TITLE
Playback on macOS is too slow (speed/2)

### ISSUE THREAD

**Issue by jbnoel-gpsw** [gopro/gopro-lib-node.gl#2]
10s scene plays in 20s.
(Sierra 10.12.6)

**Comment by cboesch-gpsw** [comment]
This might have happen because of the naive timing/framerate logic (a timer with a regular timeout ticking was calling a draw unconditionally, not taking into account any delay happening in the draw or anywhere else).

This code has been rewritten in `610f44da8ba1507080a69a784b8aada044565667` with the addition of the framerate configuration widget.

Please reopen with a test case if the issue happens again.
